config/routes.rb
Complaint::Application.routes.draw do
  root to: "denouncements#index"

  resources :denouncements do
    resources :comments, shallow: true
  end

  resources :countries

  resources :categories

  devise_for :users
end

app/models/denouncement.rb
class Denouncement < ActiveRecord::Base
  require "twitter"

  belongs_to :country
  belongs_to :category
  belongs_to :user
  has_many   :comments

  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader

  geocoded_by :address
  after_validation :geocode

  acts_as_ordered_taggable

  OPEN        = "open"
  IN_PROGRESS = "in_progress"
  SCALING     = "scaling"
  REJECTED    = "rejected"
  CLOSED      = "closed"

  WEB         = "web"
  TWITTER     = "twitter"
  SMS         = "sms"

  CLIENT = Twitter::REST::Client.new do |config|
    config.consumer_key        = "HyA83JZ04Wh7xONEMfCfbQ"
    config.consumer_secret     = "UJn6bSEKmDpcmS5yG8W7NO1xCYzMjMkOPSjdoiAMk"
    config.access_token        = "161024069-kiuq1eJPgJxnlqlNNONm9mETJQTfOsStnQoM8kXV"
    config.access_token_secret = "HUt6QpvxwdKQOpqJmbDkbSLcmMVNwanCDZQs4RHXA"
  end

  scope :parking,   -> { joins(:category).where('categories.name = ?', Category::PARKING).order(created_at: :desc) }
  scope :pollution, -> { joins(:category).where('categories.name = ?', Category::POLLUTION).order(created_at: :desc) }
  scope :theft,     -> { joins(:category).where('categories.name = ?', Category::THEFT).order(created_at: :desc) }
  scope :traffic,   -> { joins(:category).where('categories.name = ?', Category::TRAFFIC).order(created_at: :desc) }
  scope :other,     -> { joins(:category).where('categories.name = ?', Category::OTHER).order(created_at: :desc) }
  scope :supply,    -> { joins(:category).where('categories.name = ?', Category::SUPPLY).order(created_at: :desc) }

  def self.search(search, page_number)
    if search
      Denouncement.where('lower(title) like ? or lower(description) like ?',
      "%#{search.downcase}%",
      "%#{search.downcase}%").order(created_at: :desc).page page_number
    end
  end

  def self.last_tweets
    return Denouncement::CLIENT.user_timeline(count: 3)
  end

  def self.search_for_mentions
    Denouncement::CLIENT.mentions_timeline(count: 15).each do |mention|
      denouncement = Denouncement.where(title: mention.text).first_or_create do |denouncement|
        denouncement.created_at  = mention.created_at
        denouncement.status      = Denouncement::OPEN
        denouncement.via         = Denouncement::TWITTER
        denouncement.description = mention.text
        denouncement.category    = Category.where(name: Category::OTHER).first
        denouncement.image       = mention.attrs[:entities][:media].try(:first).try(:[], :media_url)
        denouncement.latitude    = mention.geo.coordinates.try(:first)
        denouncement.longitude   = mention.geo.coordinates.try(:last)
        denouncement.tweeted     = false
      end

      unless denouncement.tweeted
        Denouncement::CLIENT.update!(denouncement.title + "(vía @" + mention.user.screen_name + ")")
        denouncement.update tweeted: true
      end
    end
  end
end

app/controllers/denouncements_controller.rb
class DenouncementsController < ApplicationController
  before_action :set_denouncement, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: [:create]

  # GET /denouncements
  # GET /denouncements.json
  def index
    @denouncement = Denouncement.new
    @tags = ActsAsTaggableOn::Tag.select('DISTINCT tags.name').map{ |x| x.name}
    @tweets = Denouncement.last_tweets
    Denouncement.delay.search_for_mentions

    if params[:q]
      @denouncements = Denouncement.search(params[:q], params[:page])
    elsif params[:c]
      if params[:c] == Category::PARKING
        @denouncements = Denouncement.parking.page params[:page]
      elsif params[:c] == Category::POLLUTION
        @denouncements = Denouncement.pollution.page params[:page]
      elsif params[:c] == Category::THEFT
        @denouncements = Denouncement.theft.page params[:page]
      elsif params[:c] == Category::TRAFFIC
        @denouncements = Denouncement.traffic.page params[:page]
      elsif params[:c] == Category::SUPPLY
        @denouncements = Denouncement.supply.page params[:page]
      elsif params[:c] == Category::OTHER
        @denouncements = Denouncement.other.page params[:page]
      end
    else
      @denouncements = Denouncement.all.order(created_at: :desc).page params[:page]
    end
  end

  # GET /denouncements/1
  # GET /denouncements/1.json
  def show
    @comments = @denouncement.comments.order(:created_at).reverse_order
  end

  # GET /denouncements/new
  def new
    @denouncement = Denouncement.new
  end

  # GET /denouncements/1/edit
  def edit
    @comments = @denouncement.comments.order(:created_at).reverse_order
  end

  # POST /denouncements
  # POST /denouncements.json
  def create
    @denouncement        = Denouncement.new(denouncement_params)
    @denouncement.status = Denouncement::OPEN
    @denouncement.via    = Denouncement::WEB

    respond_to do |format|
      if @denouncement.save
        format.html { redirect_to @denouncement, notice: t('denouncement.created') }
        format.json { render action: 'show', status: :created, location: @denouncement }
      else
        format.html { render action: 'new' }
        format.json { render json: @denouncement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /denouncements/1
  # PATCH/PUT /denouncements/1.json
  def update
    respond_to do |format|
      if @denouncement.update(denouncement_params)
        format.html { redirect_to @denouncement, notice: t('denouncement.updated') }
      else
        format.html { render action: 'edit' }
        format.json { render json: @denouncement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /denouncements/1
  # DELETE /denouncements/1.json
  def destroy
    @denouncement.destroy
    respond_to do |format|
      format.html { redirect_to denouncements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_denouncement
      @denouncement = Denouncement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def denouncement_params
      params.require(:denouncement).permit(:title, :description, :via, :country_id, :category_id, :status, 
      :image, :video, :address, :latitude, :longitude, :tag_list, :user_id)
    end
end

app/helpers/denouncements_helper.rb
module DenouncementsHelper
  include Twitter::Autolink
  def status_for_select(actual_status)
    kinds = [ Denouncement::OPEN, Denouncement::IN_PROGRESS, Denouncement::SCALING, Denouncement::REJECTED, Denouncement::CLOSED ]
    translations = kinds.map { |status| I18n.translate "denouncement.status.#{status}" }

    options_for_select(translations.zip(kinds), actual_status)
  end
end

app/views/denouncements/_form.html.erb
<%= form_for @denouncement, html: { multipart: true } do |f| %>
  <% if @denouncement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@denouncement.errors.count, "error") %> prohibited this denouncement from being saved:</h2>

      <ul>
      <% @denouncement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: "4", class: "form-control", required: true %>
  </div>
  <div class="form-group category-form">
    <%= f.label :category_id %>
    <div class="row">
      <% Category.all.each do |c| %>
        <%= image_tag "#{c.name}_38px.png", class: "col-xs-2 img-responsive select_category has-tooltip", id: "#{c.id}", title: t("category.kinds.#{c.name}") %>
      <% end %>
    </div>
  </div>
  <%= f.hidden_field :category_id, class: "form-control", required: true %>
  <div class="form-group">
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list, class: "form-control", data: { tags: @tags } %>
  </div>
  <div class="form-group">
    <%= f.label :video %>
    <%= f.file_field :video, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.hidden_field :latitude %>
    <%= f.hidden_field :longitude %>
  </div>
  <article id="map-canvas">
  </article>
  <div class="submit">
    <%= f.submit "Enviar Denuncia" %>
  </div>
<% end %>

app/views/denouncements/edit.html.erb
<div class="container content">
  <div class="row">
    <!-- Complaint list -->
    <section class="col-xs-8">
      <div class="row">
        <header class="header-complaint">
          <%= link_to "Volver", denouncements_path %>
          <h1>Denuncia</h1>
        </header>

        <article class="show-complaint">
          <div class="row">
            <div class="col-xs-2 via <%= @denouncement.category.name %>">
              <%= image_tag "#{@denouncement.via}_62px.png"%>
              <%= image_tag "#{@denouncement.category.name}01_62px.png"%>
            </div>
            <figure class="col-xs-3 image">
              <%= image_tag @denouncement.image %>
            </figure>
            <div class="col-xs-7 title">
              <p><%= @denouncement.title %></p>
            </div>
          </div>
          <div class="row description">
            <div class="col-xs-2"></div>
            <div class="col-xs-10 text">
              <p><%= @denouncement.description %></p>
            </div>
          </div>
          <div class="row date">
            <div class="col-xs-2"></div>
            <div class="col-xs-10 info">
              <p><%= @denouncement.created_at.strftime("%d/%m/%Y - %I:%M %p")%></p>
            </div>
          </div>
          <div class="row status-container">
            <div class="col-xs-2"></div>
            <div class="<%= @denouncement.status %> col-xs-10 status">
              <div class="row">
                <div class="col-xs-7 state-title">
                  <p>Estado de la denuncia:</p>
                </div>
                <div class="col-xs-5 state-text">
                  <div class="box"></div>
                  <p class="state"><%= t("denouncement.status.#{@denouncement.status}") %></p>
                </div>
              </div>
            </div>
          </div>
        </article>
      </div>
      <div>
        <% if can? :destroy, @denouncement %>
          <%= link_to "Eliminar", @denouncement, :method => :delete, :confirm => "Estás seguro?",
          class: "button" %>
        <% end %>
      </div>
      <%= form_for @denouncement, html: { multipart: true } do |f| %>
        <div class="form-group">
          <label>Categoría</label>
          <%= f.collection_select :category_id, Category.all, :id, :translated_category, {selected: @denouncement.category_id}, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :status %>
          <%= select_tag "denouncement[status]", status_for_select(@denouncement.status), class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :address %><br>
          <%= f.text_field :address, class: "form-control" %>
        </div>
        <div class="submit">
          <%= f.submit "Actualizar Denuncia" %>
        </div>
      <% end %>
    </section>

    <!-- Map and comments -->
    <aside class="col-xs-4">
      <article class="map">
        <%= content_tag :div,
                        nil,
                        id: 'map',
                        data: { latitude: @denouncement.latitude, longitude: @denouncement.longitude } %>
      </article>
      <article class="comments">
        <header class="title">
          <h1>Comentarios</h1>
        </header>
        <% if @comments.blank? %>
          <p>"No existen comentarios en este momento"</p>
        <% else %>
          <%= render "comments/comments" %>
        <% end %>
        <%= render "comments/form" %>
      </article>
    </aside>
  </div>
</div>

app/views/denouncements/index.html.erb
<div class="container content">
  <div class="row">
    <!-- Complaint list -->
    <section class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
      <article class="categories">
        <h1>Categorías</h1>
        <div class="categories-filters">
          <%= link_to image_tag("all_44px.png"), denouncements_path %>
          <% Category.all.each do |c| %>
            <%= link_to image_tag("#{c.name}_44px.png"), denouncements_path(c: c.name), rel: "tooltip", title: t("category.kinds.#{c.name}") %>
          <% end %>
        </div>
      </article>

      <header class="complaints">
        <h1>Denuncias recientes</h1>
      </header>

      <% if @denouncements.blank? %>
        <article class="empty_denouncement_results">
          <% if params[:q] %>
            <%= image_tag "search_not_found.png" %>
          <% elsif params[:c] %>
            <%= image_tag "#{params[:c]}_search.png" %>
          <% end %>
        </article>
      <% else %>
        <% @denouncements.each do |denouncement| %>
          <article class="complaint">
            <% if denouncement.category.blank? %>
              <div class="col-xs-2 via other">
                <%= image_tag("#{denouncement.via}_62px.png") %>
                <%= image_tag("other01_62px.png") %>
              </div>
            <% else %>
              <div class="col-xs-2 via <%= denouncement.category.name %>">
                <%= image_tag("#{denouncement.via}_62px.png") %>
                <%= image_tag("#{denouncement.category.name}01_62px.png") %>
              </div>
            <% end %>
            <figure class="col-xs-3 image">
              <% if denouncement.image.blank? %>
                <%= image_tag "empt_image.png" %>
              <% else %>
                <%= image_tag denouncement.image %>
              <% end %>
            </figure>
            <div class="col-xs-7 description">
              <p><%= auto_link(denouncement.title).html_safe %></p>
              <%= link_to "Ver más", denouncement, type: "button", method: :get, class: "more" %>
            </div>
            <div class="row date">
              <div class="col-xs-2"></div>
              <div class="<%= denouncement.status %> col-xs-3 status">
                <div class="box"></div>
                <p class="state"><%= t("denouncement.status.#{denouncement.status}") %></p>
              </div>
              <div class="col-xs-7 info">
                <p><%= local_time(denouncement.created_at, format: "%d/%m/%Y - %I:%M %p") %></p>
              </div>
            <div>
          </article>
        <% end %>
      <% end %>

      <%= paginate @denouncements %>
    </section>

    <!-- Complaint form and twitter -->
    <aside class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
      <div class="complaint-form">
        <header>
          <h1>Denuncia aquí</h1>
          <div class="col-xs-12 border-line"></div>
          <div class="col-xs-12 white-line"></div>
        </header>
        <%= render 'form' %>
      </div>
      <div class="twitter row">
        <header>
          <h1>Twitter</h1>
        </header>
        <section class="col-xs-12">
          <% @tweets.each do |tweet| %>
            <article>
              <figure class="col-xs-3">
                <%= image_tag @tweets.first.user.profile_image_url %>
              </figure>
              <%= link_to "@#{tweet.user.name}", "http://twitter.com/#{tweet.user.name}", class: "title"%>
              <div class="col-xs-9 info">
                <p><%= auto_link(tweet.text).html_safe %></p>
                <p><%= local_time(tweet.created_at, format: "%d/%m/%Y - %I:%M %p") %></p>
              </div>
            </article>
          <% end %>
        </section>
      </div>
    </aside>
  </div>
</div>

app/views/denouncements/new.html.erb
<h1>New denouncement</h1>

<%= render 'form' %>

<%= link_to 'Back', denouncements_path %>

app/views/denouncements/show.html.erb
<div class="container content">
  <div class="row">
    <!-- Complaint list -->
    <section class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
      <div class="row">
        <header class="header-complaint">
          <%= link_to "Volver", denouncements_path %>
          <h1>Denuncia</h1>
        </header>

        <article class="show-complaint">
          <div class="row">
            <% if @denouncement.category.blank? %>
              <div class="col-xs-2 via other">
                <%= image_tag "#{@denouncement.via}_62px.png"%>
                <%= image_tag "#other01_62px.png"%>
              </div>
            <% else %>
              <div class="col-xs-2 via <%= @denouncement.category.name %>">
                <%= image_tag "#{@denouncement.via}_62px.png"%>
                <%= image_tag "#{@denouncement.category.name}01_62px.png"%>
              </div>
            <% end %>
            <figure class="col-xs-3 image">
              <% if @denouncement.image.blank? %>
                <%= image_tag "empt_image.png" %>
              <% else %>
                <%= image_tag @denouncement.image %>
              <% end %>
            </figure>
            <div class="col-xs-7 title">
              <p><%= auto_link(@denouncement.title).html_safe %></p>
            </div>
          </div>
          <% unless @denouncement.via == Denouncement::TWITTER %>
            <div class="row description">
              <div class="col-xs-2"></div>
              <div class="col-xs-10 text">
                <p><%= auto_link(@denouncement.description).html_safe %></p>
                <% unless @denouncement.video.blank? %>
                  <%= video_tag @denouncement.video, :size => "400x240", :controls => true %>
                <% end %>
              </div>
            </div>
          <% end %>
          <div class="row date">
            <div class="col-xs-2"></div>
            <div class="col-xs-10 info">
              <p><%= local_time(@denouncement.created_at, format: "%d/%m/%Y - %I:%M %p")%></p>
            </div>
          </div>
          <div class="row status-container">
            <div class="col-xs-2"></div>
            <div class="<%= @denouncement.status %> col-xs-10 status">
              <div class="row">
                <div class="col-xs-7 state-title">
                  <p>Estado de la denuncia:</p>
                </div>
                <div class="col-xs-5 state-text">
                  <div class="box"></div>
                  <p class="state"><%= t("denouncement.status.#{@denouncement.status}") %></p>
                </div>
              </div>
              <div class="row social_share">
                <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= denouncement_url %>" data-via="misdenuncias" data-lang="es" data-text="<%= @denouncement.title %>">Tweet</a>
                <div class="fb-share-button" data-href="<%= denouncement_url %>" data-type="button_count"></div>
              </div>
            </div>
          </div>
        </article>
      </div>
      <div>
        <% if can? :update, @denouncement %>
          <%= link_to "Editar", edit_denouncement_path(@denouncement), class: "button"  %>
        <% end %>
        <% if can? :destroy, @denouncement %>
          <%= link_to "Eliminar", @denouncement, :method => :delete, :confirm => "Estás seguro?", class: "button"  %>
        <% end %>
      </div>
    </section>

    <!-- Map and comments -->
    <aside class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
      <article class="map">
        <%= content_tag :div,
                        nil,
                        id: 'map',
                        data: { latitude: @denouncement.latitude, longitude: @denouncement.longitude } %>
      </article>
      <article class="comments">
        <header class="title">
          <h1>Comentarios</h1>
        </header>
        <% if @comments.blank? %>
          <p>"No existen comentarios en este momento"</p>
        <% else %>
          <%= render "comments/comments" %>
        <% end %>
        <%= render "comments/form" %>
      </article>
    </aside>
  </div>
</div>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=121365964645022";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>